apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
# configure an Aravis Camera with the Standard set of Plugins
data:
  start.sh: >
  {{ tpl (.Files.Get "config/start.sh") . | nindent 4 | replace "[[" "{{" | replace "]]" "}}" }}
  stop.sh: >
  {{ .Files.Get "config/stop.sh"}}
  liveness.sh: >
  {{ .Files.Get "config/liveness.sh"}}